"""Backend-neutral contracts for distribution-based training in ART."""

from .artifact import PreparedTrainingBatch
from .candidate import CandidateTrainingBatch
from .capture import (
    append_message,
    captured_context,
    generations,
    last_generation,
    prepend_message,
    with_tools,
)
from .prepare import (
    BatchPreparer,
    PreparationContext,
    all_generations,
    prepare,
    same_context,
)
from .preparer import (
    AllCapturedGenerations,
    DistillationPreparationError,
    FailurePolicy,
    SameContext,
    mask_failed_generation,
    strict,
)
from .types import (
    AnyRevision,
    CapturedGeneration,
    CurrentStep,
    Example,
    ForwardKL,
    Frozen,
    GenerationPart,
    Loss,
    PartSpan,
    PreparationIssue,
    PreparationReport,
    PreparedConstraints,
    RolloutRevisionSpan,
    StudentOnPolicy,
    TeacherRevision,
    TeacherView,
    TokenSpan,
    TopK,
    TopKTargetRow,
    TrainingGroupSnapshot,
    TrainingObjectives,
    TrainingTrajectorySnapshot,
)

__all__ = [
    "AnyRevision",
    "all_generations",
    "AllCapturedGenerations",
    "append_message",
    "BatchPreparer",
    "CandidateTrainingBatch",
    "CapturedGeneration",
    "captured_context",
    "CurrentStep",
    "Example",
    "ForwardKL",
    "Frozen",
    "GenerationPart",
    "generations",
    "DistillationPreparationError",
    "FailurePolicy",
    "last_generation",
    "Loss",
    "mask_failed_generation",
    "PartSpan",
    "prepend_message",
    "prepare",
    "PreparationContext",
    "PreparationReport",
    "PreparationIssue",
    "PreparedConstraints",
    "PreparedTrainingBatch",
    "RolloutRevisionSpan",
    "StudentOnPolicy",
    "strict",
    "same_context",
    "SameContext",
    "TeacherView",
    "TeacherRevision",
    "TokenSpan",
    "TopK",
    "TopKTargetRow",
    "TrainingGroupSnapshot",
    "TrainingObjectives",
    "TrainingTrajectorySnapshot",
    "with_tools",
]
