"""Backend-neutral contracts for distribution-based training in ART."""

from .artifact import PreparedTrainingBatch
from .prepare import BatchPreparer, PreparationContext
from .types import (
    AnyRevision,
    CapturedGeneration,
    CurrentStep,
    Example,
    ForwardKL,
    Frozen,
    GenerationPart,
    Loss,
    PartSpan,
    PreparationReport,
    PreparedConstraints,
    RolloutRevisionSpan,
    StudentOnPolicy,
    TeacherRevision,
    TeacherView,
    TokenSpan,
    TopK,
    TopKTargetRow,
    TrainingGroupSnapshot,
    TrainingObjectives,
    TrainingTrajectorySnapshot,
)

__all__ = [
    "AnyRevision",
    "BatchPreparer",
    "CapturedGeneration",
    "CurrentStep",
    "Example",
    "ForwardKL",
    "Frozen",
    "GenerationPart",
    "Loss",
    "PartSpan",
    "PreparationContext",
    "PreparationReport",
    "PreparedConstraints",
    "PreparedTrainingBatch",
    "RolloutRevisionSpan",
    "StudentOnPolicy",
    "TeacherView",
    "TeacherRevision",
    "TokenSpan",
    "TopK",
    "TopKTargetRow",
    "TrainingGroupSnapshot",
    "TrainingObjectives",
    "TrainingTrajectorySnapshot",
]
